# Generated by Django 5.2.3 on 2026-02-28 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_kategori_options_alter_kegiatan_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='selesai',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='waktu',
            field=models.TimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='kegiatan',
            index=models.Index(fields=['pengguna', 'tanggal'], name='tracker_keg_penggun_673073_idx'),
        ),
        migrations.AddIndex(
            model_name='kegiatan',
            index=models.Index(fields=['pengguna', 'selesai'], name='tracker_keg_penggun_e85f30_idx'),
        ),
        migrations.AddIndex(
            model_name='kegiatan',
            index=models.Index(fields=['tanggal', 'waktu'], name='tracker_keg_tanggal_8d28eb_idx'),
        ),
    ]
